"""Validate IF-40 pivot with feature/proxy disjoint ablations.

This script is intentionally isolated from the production scorer artifacts.
It reuses the enriched feature parquets generated by eval_with_raw_features.py
and writes a validation report for the thesis pivot decision.
"""
from __future__ import annotations

import argparse
import gc
import json
import time
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
from scipy.stats import norm
from sklearn.ensemble import IsolationForest
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import RobustScaler
from sklearn.svm import OneClassSVM


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data" / "processed"
OUTPUT_DIR = ROOT / "output"
MODELS_DIR = OUTPUT_DIR / "models"

EXACT_PROXY_FEATURES = {
    "same_amount_count_1h",
    "user_account_age_days",
    "user_txn_count_1h",
    "is_third_party_payment",
}

CAPTURE_DELAY_FEATURES = {"capture_delay_seconds"}

SEMANTIC_PROXY_DERIVATIVES = {
    "is_new_user",
    "is_very_new_user",
    "new_user_first_facility",
    "rapid_burst",
    "same_amount_count_24h",
}

VARIANT_DROPS = {
    "fs_disjoint_36_exact": EXACT_PROXY_FEATURES,
    "fs_disjoint_35_no_capture": EXACT_PROXY_FEATURES | CAPTURE_DELAY_FEATURES,
    "fs_semantic_30_no_proxy_derivatives": (
        EXACT_PROXY_FEATURES | CAPTURE_DELAY_FEATURES | SEMANTIC_PROXY_DERIVATIVES
    ),
}

DEFAULT_PRIMARY_VARIANT = "fs_disjoint_35_no_capture"
DEFAULT_PRIMARY_SEEDS = [11, 42, 77, 123, 2025]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=str(OUTPUT_DIR / "pivot_if40_disjoint_validation.json"),
        help="Path for the validation JSON report.",
    )
    parser.add_argument(
        "--primary-variant",
        default=DEFAULT_PRIMARY_VARIANT,
        choices=sorted(VARIANT_DROPS),
        help="Variant used for multi-seed and comparator checks.",
    )
    parser.add_argument(
        "--primary-seeds",
        default=",".join(str(s) for s in DEFAULT_PRIMARY_SEEDS),
        help="Comma-separated IF seeds for the primary variant.",
    )
    parser.add_argument(
        "--run-comparators",
        action="store_true",
        help="Train LOF and OC-SVM on the primary variant for HE4 screening.",
    )
    parser.add_argument("--lof-sample", type=int, default=200_000)
    parser.add_argument("--ocsvm-sample", type=int, default=50_000)
    return parser.parse_args()


def load_feature_list() -> List[str]:
    return json.loads((MODELS_DIR / "final_feature_list.json").read_text())


def load_enriched_splits(columns: Iterable[str]) -> Dict[str, pd.DataFrame]:
    cols = list(dict.fromkeys(columns))
    return {
        "train": pd.read_parquet(DATA_DIR / "train_features_enriched.parquet", columns=cols),
        "val": pd.read_parquet(DATA_DIR / "val_features_enriched.parquet", columns=cols),
        "test": pd.read_parquet(DATA_DIR / "test_features_enriched.parquet", columns=cols),
    }


def build_tipo_a_proxy(df: pd.DataFrame) -> np.ndarray:
    return df["status"].isin(["totally_refunded", "refunded_to_credit"]).to_numpy(np.int8)


def build_operational_proxy(df: pd.DataFrame) -> np.ndarray:
    card_test = (df["same_amount_count_1h"] >= 3).to_numpy()
    new_burst = (
        (df["user_account_age_days"] < 14) & (df["user_txn_count_1h"] >= 3)
    ).to_numpy()
    third_party_burst = (
        (df["is_third_party_payment"] == 1) & (df["user_txn_count_1h"] >= 2)
    ).to_numpy()
    return (card_test | new_burst | third_party_burst).astype(np.int8)


def build_proxies(df: pd.DataFrame) -> Dict[str, np.ndarray]:
    return {
        "tipo_a": build_tipo_a_proxy(df),
        "operational_proxy": build_operational_proxy(df),
    }


def percentile_metrics(scores: np.ndarray, y: np.ndarray) -> Dict[str, float]:
    base = float(y.mean())
    order = np.argsort(-scores)
    out: Dict[str, float] = {}
    for pct in (0.01, 0.02, 0.05, 0.10):
        k = max(1, int(np.ceil(len(scores) * pct)))
        precision = float(y[order[:k]].sum() / k)
        suffix = f"{int(pct * 100)}pct"
        out[f"p_{suffix}"] = precision
        out[f"ef_{suffix}"] = precision / base if base > 0 else 0.0
    return out


def mann_whitney_from_auc(auc: float, n_pos: int, n_neg: int) -> Dict[str, float]:
    u = float(auc * n_pos * n_neg)
    mean_u = n_pos * n_neg / 2
    sd_u = np.sqrt(n_pos * n_neg * (n_pos + n_neg + 1) / 12)
    z = (u - mean_u) / sd_u if sd_u > 0 else 0.0
    return {
        "U_statistic_from_auc": u,
        "rank_biserial_r": float(2 * auc - 1),
        "p_value_asymptotic_no_tie": float(norm.sf(z)),
    }


def evaluate_scores(scores: np.ndarray, proxies: Dict[str, np.ndarray]) -> Dict[str, Dict[str, float]]:
    results: Dict[str, Dict[str, float]] = {}
    for name, y in proxies.items():
        positives = int(y.sum())
        negatives = int(len(y) - positives)
        if positives == 0 or negatives == 0:
            continue
        auc = float(roc_auc_score(y, scores))
        block = {
            "auc": auc,
            "ap": float(average_precision_score(y, scores)),
            "base_rate": float(y.mean()),
            "n_positives": positives,
            "n_negatives": negatives,
        }
        block.update(percentile_metrics(scores, y))
        block.update(mann_whitney_from_auc(auc, positives, negatives))
        results[name] = block
    return results


def assert_quality(df: pd.DataFrame, features: List[str], split: str) -> None:
    matrix = df[features]
    if matrix.isnull().any().any():
        bad = matrix.columns[matrix.isnull().any()].tolist()
        raise ValueError(f"{split} has NaN values in {bad}")
    values = matrix.to_numpy(dtype=np.float32, copy=False)
    if not np.isfinite(values).all():
        raise ValueError(f"{split} has non-finite feature values")


def scale_splits(
    splits: Dict[str, pd.DataFrame], features: List[str]
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    x_train = splits["train"][features].to_numpy(dtype=np.float32, copy=True)
    x_val = splits["val"][features].to_numpy(dtype=np.float32, copy=True)
    x_test = splits["test"][features].to_numpy(dtype=np.float32, copy=True)

    scaler = RobustScaler(quantile_range=(5.0, 95.0)).fit(x_train)
    x_train = np.clip(scaler.transform(x_train).astype(np.float32), -10, 10)
    x_val = np.clip(scaler.transform(x_val).astype(np.float32), -10, 10)
    x_test = np.clip(scaler.transform(x_test).astype(np.float32), -10, 10)
    return x_train, x_val, x_test


def fit_if_scores(
    x_train: np.ndarray, x_val: np.ndarray, x_test: np.ndarray, seed: int
) -> Tuple[np.ndarray, np.ndarray]:
    model = IsolationForest(
        n_estimators=200,
        max_samples=512,
        max_features=0.6,
        contamination="auto",
        random_state=seed,
        n_jobs=-1,
    )
    model.fit(x_train)
    return (
        -np.asarray(model.decision_function(x_val), dtype=np.float64),
        -np.asarray(model.decision_function(x_test), dtype=np.float64),
    )


def temporal_subsample(x: np.ndarray, n: int) -> np.ndarray:
    if x.shape[0] <= n:
        return x
    idx = np.linspace(0, x.shape[0] - 1, n, dtype=int)
    return x[idx]


def comparator_scores(
    x_train: np.ndarray,
    x_val: np.ndarray,
    x_test: np.ndarray,
    lof_sample: int,
    ocsvm_sample: int,
) -> Dict[str, Tuple[np.ndarray, np.ndarray]]:
    scores: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}

    lof = LocalOutlierFactor(n_neighbors=20, novelty=True, metric="minkowski", n_jobs=-1)
    lof.fit(temporal_subsample(x_train, lof_sample))
    scores["lof"] = (
        -np.asarray(lof.decision_function(x_val), dtype=np.float64),
        -np.asarray(lof.decision_function(x_test), dtype=np.float64),
    )

    ocsvm = OneClassSVM(kernel="rbf", nu=0.05, gamma="scale")
    ocsvm.fit(temporal_subsample(x_train, ocsvm_sample))
    scores["ocsvm"] = (
        -np.asarray(ocsvm.decision_function(x_val), dtype=np.float64),
        -np.asarray(ocsvm.decision_function(x_test), dtype=np.float64),
    )
    return scores


def summarize_seed_results(seed_results: Dict[str, Dict[str, Dict[str, float]]]) -> Dict[str, Dict[str, float]]:
    summary: Dict[str, Dict[str, float]] = {}
    for proxy_name in ("operational_proxy", "tipo_a"):
        proxy_summary: Dict[str, float] = {}
        for metric in ("auc", "ap", "ef_1pct", "ef_5pct", "rank_biserial_r"):
            vals = [
                result["test"][proxy_name][metric]
                for result in seed_results.values()
                if proxy_name in result["test"]
            ]
            if not vals:
                continue
            arr = np.asarray(vals, dtype=np.float64)
            proxy_summary[f"{metric}_mean"] = float(arr.mean())
            proxy_summary[f"{metric}_std"] = float(arr.std(ddof=0))
            proxy_summary[f"{metric}_min"] = float(arr.min())
            proxy_summary[f"{metric}_max"] = float(arr.max())
        summary[proxy_name] = proxy_summary
    return summary


def he4_screening(test_results: Dict[str, Dict[str, Dict[str, float]]]) -> Dict[str, object]:
    metrics = ["auc", "ap", "p_5pct", "ef_5pct"]
    proxy = "operational_proxy"
    if proxy not in test_results["if"]:
        return {"pass": False, "reason": "operational proxy missing"}

    wins = {}
    for metric in metrics:
        if_value = test_results["if"][proxy][metric]
        best_comparator = max(
            test_results["lof"][proxy][metric],
            test_results["ocsvm"][proxy][metric],
        )
        wins[metric] = bool(if_value >= best_comparator)

    return {
        "metric_wins": wins,
        "wins_count": int(sum(wins.values())),
        "pass_3_of_4": bool(sum(wins.values()) >= 3),
    }


def audit_capture_delay(df_test: pd.DataFrame, y: np.ndarray) -> Dict[str, object]:
    delay = df_test["capture_delay_seconds"].to_numpy(dtype=np.float64)
    has_nonzero_delay = (delay != 0).astype(np.int8)
    abs_delay = np.abs(delay)

    audit = {
        "nonzero_rate": float(has_nonzero_delay.mean()),
        "mean_seconds": float(delay.mean()),
        "p99_seconds": float(np.quantile(delay, 0.99)),
        "nonzero_rate_by_proxy": {
            "positive": float(has_nonzero_delay[y == 1].mean()),
            "negative": float(has_nonzero_delay[y == 0].mean()),
        },
        "mean_seconds_by_proxy": {
            "positive": float(delay[y == 1].mean()),
            "negative": float(delay[y == 0].mean()),
        },
        "auc_delay_seconds": float(roc_auc_score(y, delay)),
        "auc_abs_delay_seconds": float(roc_auc_score(y, abs_delay)),
        "auc_nonzero_delay_flag": float(roc_auc_score(y, has_nonzero_delay)),
    }

    raw = pd.read_parquet(DATA_DIR / "test_raw.parquet", columns=["id", "captured_at"])
    if raw["id"].equals(df_test["id"]):
        captured = pd.to_datetime(raw["captured_at"], errors="coerce").notna().to_numpy(np.int8)
        audit["captured_at_coverage"] = float(captured.mean())
        audit["captured_at_coverage_by_proxy"] = {
            "positive": float(captured[y == 1].mean()),
            "negative": float(captured[y == 0].mean()),
        }
        audit["auc_captured_at_present"] = float(roc_auc_score(y, captured))
    else:
        audit["captured_at_coverage"] = "not_computed_id_order_mismatch"
    return audit


def main() -> None:
    args = parse_args()
    primary_seeds = [int(s.strip()) for s in args.primary_seeds.split(",") if s.strip()]
    out_path = Path(args.output)

    started = time.perf_counter()
    final_features = load_feature_list()
    required_columns = set(final_features) | {
        "id",
        "status",
        "same_amount_count_1h",
        "user_account_age_days",
        "user_txn_count_1h",
        "is_third_party_payment",
        "capture_delay_seconds",
    }
    splits = load_enriched_splits(required_columns)

    proxies = {
        split: build_proxies(df)
        for split, df in splits.items()
    }
    report: Dict[str, object] = {
        "generated_at": pd.Timestamp.utcnow().isoformat(),
        "feature_source": str(MODELS_DIR / "final_feature_list.json"),
        "n_rows": {split: int(len(df)) for split, df in splits.items()},
        "proxy_rates": {
            split: {name: float(y.mean()) for name, y in split_proxies.items()}
            for split, split_proxies in proxies.items()
        },
        "variants": {},
        "capture_delay_audit_test": audit_capture_delay(
            splits["test"], proxies["test"]["operational_proxy"]
        ),
    }

    primary_scaled = None
    primary_seed42_scores = None

    for variant, drops in VARIANT_DROPS.items():
        variant_started = time.perf_counter()
        features = [f for f in final_features if f not in drops]
        for split_name, df in splits.items():
            assert_quality(df, features, split_name)

        x_train, x_val, x_test = scale_splits(splits, features)

        seeds = primary_seeds if variant == args.primary_variant else [42]
        seed_results: Dict[str, Dict[str, Dict[str, Dict[str, float]]]] = {}
        for seed in seeds:
            seed_started = time.perf_counter()
            val_scores, test_scores = fit_if_scores(x_train, x_val, x_test, seed)
            seed_results[str(seed)] = {
                "val": evaluate_scores(val_scores, proxies["val"]),
                "test": evaluate_scores(test_scores, proxies["test"]),
                "elapsed_seconds": {"if_seed": round(time.perf_counter() - seed_started, 3)},
            }
            if variant == args.primary_variant and seed == 42:
                primary_seed42_scores = (val_scores, test_scores)

        variant_report = {
            "n_features": len(features),
            "features": features,
            "dropped_features": sorted(drops),
            "exact_proxy_feature_overlap": sorted(set(features) & EXACT_PROXY_FEATURES),
            "semantic_proxy_derivative_overlap": sorted(
                set(features) & SEMANTIC_PROXY_DERIVATIVES
            ),
            "seeds": seed_results,
            "summary": summarize_seed_results(seed_results),
            "elapsed_seconds": round(time.perf_counter() - variant_started, 3),
        }
        report["variants"][variant] = variant_report

        if variant == args.primary_variant:
            primary_scaled = (x_train, x_val, x_test)
        else:
            del x_train, x_val, x_test
            gc.collect()

    if args.run_comparators:
        if primary_scaled is None:
            raise RuntimeError("Primary variant was not scaled")
        x_train, x_val, x_test = primary_scaled
        comp_started = time.perf_counter()
        comparator_eval: Dict[str, Dict[str, Dict[str, Dict[str, float]]]] = {}

        if primary_seed42_scores is None:
            primary_seed42_scores = fit_if_scores(x_train, x_val, x_test, 42)
        comparator_eval["if"] = {
            "val": evaluate_scores(primary_seed42_scores[0], proxies["val"]),
            "test": evaluate_scores(primary_seed42_scores[1], proxies["test"]),
        }

        for model_name, (val_scores, test_scores) in comparator_scores(
            x_train,
            x_val,
            x_test,
            args.lof_sample,
            args.ocsvm_sample,
        ).items():
            comparator_eval[model_name] = {
                "val": evaluate_scores(val_scores, proxies["val"]),
                "test": evaluate_scores(test_scores, proxies["test"]),
            }

        report["comparators"] = {
            "variant": args.primary_variant,
            "lof_sample": args.lof_sample,
            "ocsvm_sample": args.ocsvm_sample,
            "results": comparator_eval,
            "he4_screening": he4_screening(
                {name: block["test"] for name, block in comparator_eval.items()}
            ),
            "elapsed_seconds": round(time.perf_counter() - comp_started, 3),
        }

    report["elapsed_seconds"] = round(time.perf_counter() - started, 3)
    out_path.write_text(json.dumps(report, indent=2))
    print(json.dumps({
        "output": str(out_path),
        "elapsed_seconds": report["elapsed_seconds"],
        "primary_variant": args.primary_variant,
        "run_comparators": args.run_comparators,
    }, indent=2))


if __name__ == "__main__":
    main()
